
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalytic-api-stoopidpc
  namespace: catalytic-lattice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: catalytic-api
  template:
    metadata:
      labels:
        app: catalytic-api
        environment: stoopidpc
    spec:
      containers:
      - name: api
        image: catalytic/api:lightweight
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: development
        - name: LOW_RESOURCE_MODE
          value: "true"
        - name: MAX_CONNECTIONS
          value: "50"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: catalytic-api-service
  namespace: catalytic-lattice
spec:
  selector:
    app: catalytic-api
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort  # Use NodePort for local access
