name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: projects/package-lock.json

    - name: Install dependencies
      run: |
        cd projects
        npm ci

    - name: Lint code
      run: |
        cd projects
        npm run lint

    - name: Type check
      run: |
        cd projects
        npm run typecheck

    - name: Run tests
      run: |
        cd projects
        npm run test

    - name: Build packages
      run: |
        cd projects
        npm run build:parallel

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: projects/package-lock.json

    - name: Install dependencies
      run: |
        cd projects
        npm ci

    - name: Run security audit
      run: |
        cd projects
        npm audit --audit-level=moderate

    - name: Check for outdated dependencies
      run: |
        cd projects
        npm outdated || true