apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 30s
      
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: catalytic_saas
    user: catalytic
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400