# API Service
apiVersion: v1
kind: Service
metadata:
  name: catalytic-api-service
  namespace: catalytic-lattice
  labels:
    app: catalytic-api
spec:
  type: LoadBalancer
  selector:
    app: catalytic-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600

---
# Internal API Service for Workers
apiVersion: v1
kind: Service
metadata:
  name: catalytic-api-internal
  namespace: catalytic-lattice
  labels:
    app: catalytic-api
spec:
  type: ClusterIP
  selector:
    app: catalytic-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: catalytic-lattice
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: catalytic-lattice
  labels:
    app: postgres
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres

---
# Ingress for API
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalytic-api-ingress
  namespace: catalytic-lattice
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.catalytic-lattice.example.com
    secretName: catalytic-tls-secret
  rules:
  - host: api.catalytic-lattice.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: catalytic-api-service
            port:
              number: 80