apiVersion: v2
name: catalytic-computing
description: Production-ready Catalytic Computing deployment for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - catalytic-computing
  - lattice
  - memory-efficient
  - gpu-acceleration
home: https://github.com/catalytic-computing/catalytic-computing
sources:
  - https://github.com/catalytic-computing/catalytic-computing
maintainers:
  - name: Catalytic Computing Team
    email: admin@catalytic-computing.io
dependencies:
  - name: redis
    version: "17.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "15.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled