# Prometheus Configuration for Catalytic Computing SaaS
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

  external_labels:
    monitor: 'catalytic-saas'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Rule files
rule_files:
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # SaaS API metrics
  - job_name: 'saas-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['saas-api:8000']
        labels:
          service: 'saas-api'
          component: 'api'

  # Webhook Service metrics
  - job_name: 'webhook-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['webhook-service:9090']
        labels:
          service: 'webhook-service'
          component: 'webhooks'

  # PostgreSQL exporter (if deployed)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'
          component: 'database'

  # Redis exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          component: 'cache'

  # Node/Docker metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          component: 'infrastructure'

  # Nginx metrics (if nginx-prometheus-exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'
          component: 'proxy'

