apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalytic-saas-hpa
  namespace: catalytic-saas
  labels:
    app: catalytic-saas-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalytic-saas-api

  minReplicas: 3
  maxReplicas: 20

  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

  # Custom metrics (if Prometheus adapter is installed)
  # - type: Pods
  #   pods:
  #     metric:
  #       name: http_requests_per_second
  #     target:
  #       type: AverageValue
  #       averageValue: "1000"

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100  # Double the pods
        periodSeconds: 60
      - type: Pods
        value: 4    # Or add 4 pods
        periodSeconds: 60
      selectPolicy: Max  # Choose whichever scales up faster

    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50   # Remove 50% of pods
        periodSeconds: 60
      - type: Pods
        value: 2    # Or remove 2 pods
        periodSeconds: 60
      selectPolicy: Min  # Choose whichever scales down slower
