apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalytic-saas
  namespace: catalytic-saas
  labels:
    app: catalytic-saas-api

---
# Role for accessing secrets and configmaps
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: catalytic-saas-role
  namespace: catalytic-saas
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
# RoleBinding to grant the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalytic-saas-rolebinding
  namespace: catalytic-saas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: catalytic-saas-role
subjects:
- kind: ServiceAccount
  name: catalytic-saas
  namespace: catalytic-saas
