[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.git
  | \.venv
  | build
  | dist
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
known_first_party = ["analytics", "event_sourcing", "security", "multi_tenant", "ml_pipeline", "orchestration"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    "aiokafka.*",
    "asyncio_mqtt.*",
    "plotly.*",
    "pandas.*",
    "numpy.*",
    "sklearn.*",
    "tensorflow.*",
    "torch.*",
    "mlflow.*",
    "kubernetes.*",
    "pulsar.*"
]
ignore_missing_imports = true

[tool.vulture]
exclude = ["build/", "dist/", ".venv/"]
ignore_decorators = ["@app.route", "@require_auth"]
ignore_names = ["setUp", "tearDown"]
min_confidence = 80
paths = ["."]

[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv"]
skips = ["B101", "B601"]  # Skip assert statements and shell injection (paramiko usage)

[tool.pydocstyle]
convention = "google"
add_ignore = "D100,D101,D102,D103,D104,D105,D107"  # Ignore missing docstrings during transition