version: '3.8'

services:
  app:
    image: go-deployment-demo:1.0.0
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - VERSION=1.0.0
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M
      placement:
        max_replicas_per_node: 2
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - go-demo-network

networks:
  go-demo-network:
    driver: overlay
    attachable: true
