#!/usr/bin/env python3
"""
Quick test to verify Unicode encoding fix works
"""
import sys
from pathlib import Path

# Sample report with Unicode characters (matching what the agents generate)
sample_report = """# Unified Project Management Report
**Generated:** 2025-10-20 16:15:00
**Orchestrator:** master-orchestrator-test

## Strategic Overview
### Roadmap Status
- Master Implementation Plan: 14.3% complete
  Progress: ████░░░░░░ 14.3%
  ⚠️ Blockers: 2

- Plugin Roadmap 2025: 0.0% complete
  Progress: ░░░░░░░░░░ 0.0%

## Log Analysis
### Summary (Last 24h)
INFO      ####------ 27 entries (87.1%)
WARNING   #--------- 4 entries (12.9%)

⚠️ **High Error Rate Detected: 12.9%**

## Progress Tracking
Current metrics would appear here

## System Health
- ✓ strategic_planner: running
- ✓ log_analyzer: running
- ✗ progress_tracker: error

---
*Generated by Master Orchestrator - Agentic Project Management System*
"""

def test_unicode_output():
    """Test Unicode output with fallback mechanism"""
    print("=" * 80)
    print("TESTING UNICODE ENCODING FIX")
    print("=" * 80)

    # Try to reconfigure stdout for UTF-8 (Python 3.7+)
    utf8_enabled = False
    try:
        if hasattr(sys.stdout, 'reconfigure'):
            sys.stdout.reconfigure(encoding='utf-8')
            utf8_enabled = True
            print("\n✅ Console configured for UTF-8 output")
    except Exception as e:
        print(f"\n⚠️  Could not enable UTF-8 console: {e}")

    print(f"Current stdout encoding: {sys.stdout.encoding}")
    print("\n" + "=" * 80)
    print("ATTEMPTING TO PRINT REPORT WITH UNICODE CHARACTERS")
    print("=" * 80 + "\n")

    # Try to print with UTF-8, fallback to ASCII-safe version
    try:
        print(sample_report)
        print("\n✅ SUCCESS: Report printed with Unicode characters!")
    except UnicodeEncodeError as e:
        print(f"\n⚠️  UnicodeEncodeError detected: {e}")
        print("\nApplying ASCII fallback...\n")

        # Replace Unicode characters with ASCII alternatives
        safe_report = sample_report
        unicode_replacements = {
            '✓': '[OK]',
            '✗': '[X]',
            '✅': '[DONE]',
            '❌': '[FAIL]',
            '🔄': '[ACTIVE]',
            '⏸️': '[PAUSE]',
            '🚫': '[BLOCK]',
            '⚠️': '[!]',
            '█': '#',
            '░': '-',
            '📊': '[CHART]',
            '📰': '[NEWS]'
        }
        for unicode_char, ascii_char in unicode_replacements.items():
            safe_report = safe_report.replace(unicode_char, ascii_char)

        print(safe_report)
        print("\n✅ SUCCESS: Report printed with ASCII fallback!")
        print("[Note: Unicode characters replaced. Full version can be saved to file.]")

    # Test file save
    print("\n" + "=" * 80)
    print("TESTING FILE SAVE WITH FULL UNICODE")
    print("=" * 80 + "\n")

    test_file = Path("C:/Users/Corbin/projects/agents/test-unicode-report.md")
    try:
        with open(test_file, 'w', encoding='utf-8') as f:
            f.write(sample_report)
        print(f"✅ Report saved with full Unicode to: {test_file}")
        print(f"File size: {test_file.stat().st_size} bytes")
    except Exception as e:
        print(f"❌ Error saving file: {e}")

    print("\n" + "=" * 80)
    print("TEST COMPLETE")
    print("=" * 80)

if __name__ == "__main__":
    test_unicode_output()
