apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: default
  labels:
    app: multi-container
spec:
  containers:
  - name: main-app
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: sidecar-logger
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Logging at $(date)" >> /var/log/app.log; sleep 10; done']
    volumeMounts:
    - name: log-volume
      mountPath: /var/log

  - name: init-data
    image: busybox
    command: ['sh', '-c', 'echo "<h1>Hello from Kubernetes!</h1>" > /work-dir/index.html']
    volumeMounts:
    - name: shared-data
      mountPath: /work-dir

  volumes:
  - name: shared-data
    emptyDir: {}
  - name: log-volume
    emptyDir: {}