apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-sectest-reports-pvc
  namespace: ml-sectest
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-sectest-logs-pvc
  namespace: ml-sectest
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
