---
apiVersion: v1
kind: Service
metadata:
  name: ml-sectest-api
  namespace: ml-sectest
  labels:
    app: ml-sectest-framework
    component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  selector:
    app: ml-sectest-framework
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  sessionAffinity: None
