apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  namespace: mcp-system
  labels:
    app: mcp-system
    component: config
data:
  unified_config.json: |
    {
      "services": {
        "mcp_servers": {
          "filesystem": {
            "enabled": true,
            "command": "cmd",
            "args": ["/c", "npx", "-y", "@modelcontextprotocol/server-filesystem"],
            "path": "/app/data",
            "health_check": {
              "enabled": true,
              "endpoint": "/health",
              "interval": 30
            },
            "retry_policy": {
              "max_retries": 3,
              "backoff": "exponential",
              "initial_delay": 1000
            },
            "capabilities": ["read", "write", "list", "search"]
          },
          "financial-stochastic": {
            "enabled": true,
            "command": "node",
            "args": ["/app/mcp-servers/financial/stochastic/src/index.js"],
            "port": 3001,
            "capabilities": ["gbm", "heston", "merton", "ou_process", "cir"],
            "rate_limit": {
              "requests_per_minute": 1000,
              "burst_size": 100
            },
            "health_check": {
              "enabled": true,
              "endpoint": "/health",
              "interval": 30
            }
          }
        },
        "agents": {
          "director": {
            "enabled": true,
            "type": "coordination",
            "port": 8000,
            "max_concurrent_tasks": 50,
            "scheduling_algorithm": "priority_queue",
            "capabilities": ["orchestration", "workflow", "task_distribution"],
            "health_check": {
              "enabled": true,
              "endpoint": "/health",
              "interval": 30
            },
            "performance": {
              "max_memory_mb": 1024,
              "timeout_seconds": 300
            }
          },
          "observatory": {
            "enabled": true,
            "type": "monitoring",
            "port": 8080,
            "metrics_interval": 5000,
            "retention_days": 30,
            "capabilities": ["monitoring", "metrics", "logging", "alerting"],
            "health_check": {
              "enabled": true,
              "endpoint": "/health",
              "interval": 15
            },
            "database": {
              "type": "sqlite",
              "path": "/app/database/observatory.db"
            }
          }
        },
        "gateway": {
          "enabled": true,
          "port": 9000,
          "cors": {
            "enabled": true,
            "origins": ["*"],
            "methods": ["GET", "POST", "PUT", "DELETE"],
            "headers": ["*"]
          },
          "rate_limiting": {
            "enabled": true,
            "requests_per_minute": 1000,
            "burst_size": 200
          },
          "authentication": {
            "enabled": true,
            "methods": ["jwt", "api_key", "basic"],
            "jwt": {
              "expiry_hours": 24,
              "algorithm": "HS256"
            },
            "api_key": {
              "expiry_days": 365,
              "header": "X-API-Key"
            },
            "rate_limiting": {
              "max_login_attempts": 10,
              "lockout_duration_minutes": 15
            }
          },
          "circuit_breaker": {
            "enabled": true,
            "failure_threshold": 5,
            "timeout": 60,
            "success_threshold": 3
          }
        }
      },
      "infrastructure": {
        "logging": {
          "level": "INFO",
          "format": "json",
          "destinations": ["file", "console"],
          "file": {
            "path": "/app/logs",
            "rotation": {
              "enabled": true,
              "max_size": "100MB",
              "max_files": 10,
              "compress": true
            }
          },
          "console": {
            "colorize": false,
            "timestamp": true
          }
        },
        "monitoring": {
          "metrics_enabled": true,
          "tracing_enabled": true,
          "sample_rate": 0.1,
          "exporters": {
            "prometheus": {
              "enabled": true,
              "port": 9090,
              "path": "/metrics"
            },
            "jaeger": {
              "enabled": true,
              "endpoint": "http://jaeger-collector:14268/api/traces"
            }
          }
        },
        "storage": {
          "cache": {
            "enabled": true,
            "type": "redis",
            "ttl_seconds": 300,
            "max_size_mb": 256,
            "redis": {
              "host": "redis-service",
              "port": 6379,
              "db": 0,
              "password": "${REDIS_PASSWORD}",
              "max_connections": 20,
              "key_prefix": "mcp:"
            }
          },
          "database": {
            "type": "postgresql",
            "host": "postgresql-service",
            "port": 5432,
            "database": "mcp_production",
            "username": "mcp_user",
            "password": "${POSTGRES_PASSWORD}",
            "connection_pool": {
              "min_connections": 5,
              "max_connections": 20
            }
          }
        },
        "security": {
          "tls": {
            "enabled": true,
            "cert_path": "/etc/ssl/certs",
            "key_path": "/etc/ssl/private"
          },
          "api_keys": {
            "enabled": true,
            "rotation_days": 90
          },
          "encryption": {
            "at_rest": true,
            "in_transit": true
          }
        },
        "resilience": {
          "circuit_breaker": {
            "enabled": true,
            "threshold": 5,
            "timeout": 60000,
            "reset_timeout": 30000
          },
          "retry": {
            "enabled": true,
            "max_attempts": 3,
            "backoff": "exponential",
            "initial_delay": 1000,
            "max_delay": 10000
          },
          "timeout": {
            "default": 30000,
            "long_running": 300000
          }
        }
      },
      "environment": {
        "current": "production",
        "paths": {
          "base": "/app",
          "agents": "/app/agents",
          "mcp_servers": "/app/mcp-servers",
          "shared": "/app/shared",
          "configs": "/app/configs",
          "logs": "/app/logs"
        }
      },
      "features": {
        "hot_reload": false,
        "auto_discovery": true,
        "health_checks": true,
        "distributed_tracing": true,
        "message_queue": true,
        "api_gateway": true,
        "circuit_breakers": true,
        "authentication": true,
        "workflow_engine": true,
        "redis_cache": true
      }
    }