apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mcp-base
  annotations:
    description: "MCP & Agent Architecture Base Configuration"

resources:
  - namespace.yaml
  - configmap.yaml
  - redis.yaml
  - api-gateway.yaml
  - observatory-agent.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mcp-system
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/part-of: mcp-architecture

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
  
images:
  - name: mcp/api-gateway
    newTag: v1.0.0
  - name: mcp/observatory-agent
    newTag: v1.0.0

configMapGenerator:
  - name: mcp-build-info
    literals:
      - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - VERSION=v1.0.0
      - GIT_COMMIT=$(git rev-parse HEAD)

secretGenerator:
  - name: mcp-secrets
    literals:
      - JWT_SECRET=super-secret-jwt-key-change-in-production
      - REDIS_PASSWORD=mcp-redis-prod-pass
      - POSTGRES_PASSWORD=mcp-postgres-prod-pass

generatorOptions:
  disableNameSuffixHash: false
  
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/config.linkerd.io~1skip-inbound-ports
        value: "9000,8080"