apiVersion: v1
kind: Namespace
metadata:
  name: mcp-system
  labels:
    name: mcp-system
    version: v1
    component: infrastructure
  annotations:
    description: "MCP & Agent Architecture Namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mcp-resource-quota
  namespace: mcp-system
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mcp-limit-range
  namespace: mcp-system
spec:
  limits:
  - default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "250m"
    type: Container